# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d6e08a78991bc8d013961614cda3a77df26e0ad06aae6b38d349ce2422695ea43193ccafd98c639242dd38f28ce1d679cca5f8d6697ef4bcb0d32bef933571e

test:
  secret_key_base: afc664963cc7d19e6aa3eeecca10505901e467f4a881c93db52b420cbd5623db69d8821d461ab59006de9b139a8a555266342b6296e43f7fffe2e96b1e11d816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
